/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class clz_JniTest */

#ifndef _Included_clz_JniTest
#define _Included_clz_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     clz_JniTest
 * Method:    callJavaStaticMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_clz_JniTest_callJavaStaticMethod
  (JNIEnv *, jobject);

/*
 * Class:     clz_JniTest
 * Method:    callJavaInstanceMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_clz_JniTest_callJavaInstanceMethod
  (JNIEnv *, jobject);

JNIEXPORT jstring JNICALL Java_clz_JniTest_refrenceNewString
        (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
